# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetSing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetSing

  pod "youtube-ios-player-helper", "~> 0.1.1"
  pod "Alamofire"
  pod 'YouTubePlayer'
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'YoutubeSourceParserKit'

end
